name: Moose Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Swift Version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version: "13.1"

    - name: Gather code coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/MoosePackageTests.xctest/Contents/MacOS/MoosePackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: fail
        files: ./coverage_report.lcov
        verbose: true
