name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: swift-actions/setup-swift@v1.18.0
      with:
        swift-version: "5.7"
    - name: Get Swift Version
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
